### ISSUE TITLE
error: Uncaught exception: Error: spawn git ENOENT 

### ISSUE THREAD

**Issue by diskroma** [tpope/vim-fugitive#1511]
When running :Gdiffsplit im getting this error:
```
[coc.nvim] error: Uncaught exception: Error: spawn git ENOENT                                                                                                                                                
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Im on NVIM v0.4.3.

**Comment by tpope** [comment]
Does it happen if coc.nvim isn't installed?

**Comment by diskroma** [comment]
After uninstalling and reinstalling coc, i can no longer reproduce it.
Maybe it was a issue with coc.
